databases:
  - name: digitaldaisy
    databaseName: digitaldaisy
    user: digitaldaisy

services:
  - type: web
    name: digitaldaisy
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn digitaldaisy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: digitaldaisy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4