# Generated by Django 4.2.3 on 2023-07-24 09:42

import datetime
import django.core.validators
from django.db import migrations, models
import login_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='Username')),
                ('empid', models.CharField(max_length=20, null=True, verbose_name='Employee ID')),
                ('permission', models.CharField(choices=[('given', 'given'), ('not given', 'not given')], max_length=50, null=True, verbose_name='Permission')),
                ('work_time', models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=28800))], verbose_name='Work Time')),
                ('remaining_time', models.DurationField(default=datetime.timedelta(seconds=28800), verbose_name='Remaining Time')),
                ('designation', models.CharField(max_length=50, null=True, verbose_name='Designation')),
                ('department', models.CharField(max_length=50, null=True, verbose_name='Department')),
                ('phone_number', models.CharField(max_length=10, null=True, verbose_name='Phone Number')),
                ('login_counter', models.IntegerField(default=0, null=True, verbose_name='No. Of LogIns')),
                ('logout_counter', models.IntegerField(default=0, null=True, verbose_name='No. Of LogOuts')),
                ('intime', models.CharField(max_length=200, null=True, verbose_name='Current Login Time')),
                ('out_time', models.CharField(max_length=200, null=True, verbose_name='Previous LogOut Time')),
                ('duration_time', models.CharField(max_length=200, null=True, verbose_name='Last Login Duration')),
                ('login_list', login_system.models.ListField(null=True, token=',', verbose_name='Login List')),
                ('logout_list', login_system.models.ListField(null=True, token=',', verbose_name='Logout List')),
                ('duration_list', login_system.models.ListField(null=True, token=',', verbose_name='Login Duration List')),
                ('daily_login_list', login_system.models.ListField(null=True, token=',', verbose_name='Daily Login List')),
                ('weekly_login_list', login_system.models.ListField(null=True, token=',', verbose_name='Weekly Login List')),
                ('monthly_login_list', login_system.models.ListField(null=True, token=',', verbose_name='Monthly Login List')),
                ('daily_logout_list', login_system.models.ListField(null=True, token=',', verbose_name='Daily Logout List')),
                ('weekly_logout_list', login_system.models.ListField(null=True, token=',', verbose_name='Weekly Logout List')),
                ('monthly_logout_list', login_system.models.ListField(null=True, token=',', verbose_name='Monthly Logout List')),
                ('daily_duration_list', login_system.models.ListField(null=True, token=',', verbose_name='Daily Duration List')),
                ('weekly_duration_list', login_system.models.ListField(null=True, token=',', verbose_name='Weekly Duration List')),
                ('monthly_duration_list', login_system.models.ListField(null=True, token=',', verbose_name='Monthly Duration List')),
                ('login_time', models.DateTimeField(blank=True, null=True, verbose_name='Login Time')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout Time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Login Duration')),
                ('last_weekly_update', models.DateField(null=True, verbose_name='Last Weekly Update')),
                ('last_monthly_update', models.DateField(null=True, verbose_name='Last Monthly Update')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_teamLead', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
