# Generated by Django 4.2.1 on 2023-07-31 07:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remaining_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Remaining Time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=28800))], verbose_name='Work Time'),
        ),
    ]
