# Generated by Django 4.2.1 on 2023-08-01 07:20

from django.db import migrations
import login_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_alter_employee_remaining_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='monthly_work_time_list',
            field=login_system.models.ListField(null=True, token=',', verbose_name='Monthly Work Time List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_work_time_list',
            field=login_system.models.ListField(null=True, token=',', verbose_name='Weekly Work Time List'),
        ),
    ]
