# Generated by Django 4.2.1 on 2023-08-01 07:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_employee_monthly_work_time_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='previous_work_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=28800))], verbose_name='Previous Work Time'),
        ),
    ]
