# Generated by Django 4.2.1 on 2023-08-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0004_employee_previous_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_HR',
            field=models.BooleanField(default=False),
        ),
    ]
