# Generated by Django 4.2.1 on 2023-08-02 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0005_employee_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='yearly_duration_list',
            field=login_system.models.ListField(null=True, token=',', verbose_name='Yearly Duration List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='yearly_login_list',
            field=login_system.models.ListField(null=True, token=',', verbose_name='Yearly Login List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='yearly_logout_list',
            field=login_system.models.ListField(null=True, token=',', verbose_name='Yearly Logout List'),
        ),
        migrations.CreateModel(
            name='IndividualEmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
