# Generated by Django 4.2.1 on 2023-08-02 11:32

from django.db import migrations
import login_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0006_employee_yearly_duration_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='yearly_login_dates',
            field=login_system.models.ListField(null=True, token=',', verbose_name='Yearly Login Dates'),
        ),
    ]
