# Generated by Django 4.2.1 on 2023-08-08 12:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0007_employee_yearly_login_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='psudo_remaining_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Psudo Remaining Time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='psudo_work_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=28800))], verbose_name='Psudo Work Time'),
        ),
    ]
