# Generated by Django 4.2.1 on 2023-08-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0008_employee_psudo_remaining_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auto_logout_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
