# Generated by Django 4.2.1 on 2023-08-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0010_employee_last_login_at_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
