# Generated by Django 4.2.1 on 2023-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0011_remove_employee_last_login_at_remove_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.CharField(choices=[('given', 'given'), ('not given', 'not given')], default='given', max_length=50, null=True, verbose_name='Permission'),
        ),
    ]
